version: '3.8'

services:
  secrets_postgres:
    image: postgres:12.6-alpine
    command: ["postgres", "-c", "log_statement=all", "-c", "shared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - ./queries:/queries
      - ./initdb:/initdb
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    expose:
      - 5432
    ports:
      - "7001:5432"
    restart: unless-stopped

